# Generated by Django 4.2.7 on 2023-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="material",
        ),
        migrations.AddField(
            model_name="application",
            name="material",
            field=models.ManyToManyField(to="customer.material"),
        ),
    ]
